環境構築()
traPtitech/Emoine_R pull request #2
Opened 2022-10-04 13:00 UTC by s9-sukyu

2022-10-09 10:01 UTC, seigo2016 commented on main.go
> +	e.Logger.Fatal(e.Start(":8000"))
OpenAPIのdocsに合わせてポート変更お願いします。(ref: https://q.trap.jp/messages/7add8ab8-d70f-4858-8d08-33f74888261d)

2022-10-09 10:03 UTC, seigo2016 commented on docker-compose.yml
> +    image: mysql
これは個人的な意見ですが、適切にイメージバージョン指定があったほうが好ましい気がします。or latest

2022-10-13 12:24 UTC, s9-sukyu commented
MySQL用のadminerは消しておいたほうがいいですか？

2022-10-30 13:24 UTC, s9-sukyu commented on main.go
> +	e.Logger.Fatal(e.Start(":8000"))
変更しました

2022-10-30 13:24 UTC, s9-sukyu commented on docker-compose.yml
> +    image: mysql
バージョン8を指定しました

2022-10-31 06:57 UTC, seigo2016 requested changes

2022-10-31 06:57 UTC, seigo2016 commented on docker-compose.yml
> +    command: --default-authentication-plugin=mysql_native_password
Edited
```
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
```
などのutf8mb4の文字コードを使用した方がいいと思います。
(utf8だと絵文字や漢字などは十分にサポートされておらず、特に理由がなければutf8mb4推奨のはずです)

2022-10-31 06:57 UTC, seigo2016 commented on README.md
> +docker-compose up -d
`docker compose`コマンド(Compose v2)もあります。これはPythonからGoに再実装し、docker-composeを置き換えることを目標としたもので、Docker Engine（Docker CLI）に含まれています。2023年にCompose v1(docker-composeコマンド)は非推奨になるので、検討が必要かもしれません。

2022-11-01 00:22 UTC, merged