OAuthの実装
traPtitech/Emoine_R pull request #26
Opened 2023-01-09 13:32 UTC by s9-sukyu

Close #7

2023-02-10 03:54 UTC, ras0q commented
diffがやや見にくいのでもう一度`git merge origin/main`をしてほしいです(バグ？)

2023-02-10 04:11 UTC, s9-sukyu commented
already up to dateでした
mainのマージを取り込もうにも`git pull`をしても読み込んでくれなかったので`git rebase`しちゃったけど、もしかして本来は`git merge origin/main`をすべきでしたか

2023-02-10 04:21 UTC, ras0q commented
`git pull origin main`とかだったら取り込めたかも？あんま自信ないです

2023-02-10 04:24 UTC, ras0q commented
コンフリクト激しくなかったらもう1回rebaseしてforce pushしちゃってもい位と思います

2023-02-10 05:04 UTC, ras0q requested changes
レビューしました！

2023-02-10 05:04 UTC, ras0q commented on handler/oauth.go
> +	codeChallenge := base64url.Encode(bytesCodeChallenge[:])
多分ここは外部パッケージを使わなくても標準パッケージの`encoding/base64`の`base64.RawURLEncoding.EncodeToString`で同じことができそうです

2023-02-10 05:04 UTC, ras0q commented on handler/oauth.go
> +	codeVerifier := string(bytesCodeVerifier)
`codeVerifier`51行目でしか使ってないなら変数定義する意義薄そうです
51行目を`sess.Values["CodeVerifier"] = string(bytesCodeVerifier)`にするほうが簡潔そう

2023-02-10 05:04 UTC, ras0q commented on handler/oauth.go
> +}
すでに実装してもらった状態からこれをやるかどうかは任せますが、ここらへんは準標準パッケージの https://pkg.go.dev/golang.org/x/oauth2 を使うと自前で構造体を定義しなくてもいい感じにやってくれます
https://github.com/ras0q/traq-oauth2/blob/main/example/webapp/main.go とかが参考になれば嬉しいです

2023-02-10 05:04 UTC, ras0q commented on handler/oauth.go
> +}
ここ最後改行入れてくれるとよさ

2023-04-09 14:31 UTC, ras0q requested changes
いくつかレビューしました:eyes:

2023-04-09 14:31 UTC, ras0q commented on handler/oauth.go
> +}
omitemptyにする必要なさそうです

2023-04-09 14:31 UTC, ras0q commented on handler/oauth.go
> +	params := OAuthParams{ResponseType: "code", ClientID: ClientID, CodeChallengeMethod: "S256"}
`params`すぐに使うわけじゃないので`codeChallenge`を計算してから作った方が見やすいと思います

2023-04-09 14:31 UTC, ras0q commented on handler/oauth.go
> +	sess.Values["CodeVerifier"] = string(bytesCodeVerifier)
他のkeyが小文字始まりなので合わせてほしいです:pray:

2023-04-09 14:31 UTC, ras0q commented on handler/oauth.go
> +		"code": {code}, "code_verifier": {codeVerifier}}
ここできれば一行ずつ書いてほしいです (見にくいので)

2023-04-10 14:31 UTC, ras0q reviewed
見ました:eyes:

2023-04-10 14:31 UTC, ras0q commented on handler/oauth.go
> +		"code_verifier": {codeVerifier}}
こっちの方が一般的かな
```suggestion
		"code_verifier": {codeVerifier},
	}
```

2023-04-10 14:31 UTC, ras0q commented on handler/oauth.go
> +type AuthResponse struct {
好みなんですがここあけてほしいです
```suggestion
}

type AuthResponse struct {
```

2023-04-10 14:31 UTC, ras0q commented on handler/oauth.go
> +)
constでよさそう

2023-04-10 14:31 UTC, ras0q commented on handler/oauth.go
> +	codeChallenge := base64.RawURLEncoding.EncodeToString(bytesCodeChallenge[:])
Go公式のスタイルガイドじゃないので強制力弱いんですが、変数名に型名が入ってるのはあまり好ましくないです
使うのは`codeVerifier`と`codeChallenge`だけで`byteCodeVerifier`と`byteCodeChallenge`は一時的な変換に使うだけなので1文字変数とかでいいと思います
(traq-oauth2だと`b`と`h`にしてた https://github.com/ras0q/traq-oauth2/blob/main/pkce.go)
https://google.github.io/styleguide/go/decisions#repetitive-with-type

2023-04-10 14:31 UTC, ras0q commented on handler/oauth.go
> +	sess.Options = &SessionOptionsDefault
これって毎回指定しないとダメなやつですか？

2023-04-11 00:52 UTC, s9-sukyu commented on handler/oauth.go
> +}
どれが該当の構造体かわからなかったのでそのままにしてあります

2023-04-11 00:52 UTC, s9-sukyu commented on handler/oauth.go
> +type AuthResponse struct {
エディタにGit拡張を入れたので、エディタ上だとs9, 3ヶ月前 | 1 author (s9)が見えてててっきり改行されてるかと思ってました。
修正します

2023-04-11 00:52 UTC, s9-sukyu commented on handler/oauth.go
> +	codeChallenge := base64.RawURLEncoding.EncodeToString(bytesCodeChallenge[:])
byteCodeVerifierは51行目にも使われているのでbにするとコードが追いにくくなりそうです。
codeVerifierという名前にしましたが、変更が必要ならお伝えいただきたいです

2023-04-11 00:52 UTC, s9-sukyu commented on handler/oauth.go
> +	sess.Options = &SessionOptionsDefault
OAuthGenerateCodeHandlerが呼ばれるたびにcodeChallengeが変化するので、必要かなと考えています
もしかして51行目の`sess.Options = &SessionOptionsDefault`の話ですか？

2023-04-11 04:17 UTC, ras0q commented on handler/oauth.go
> +	sess.Options = &SessionOptionsDefault
optionの方ですね

2023-04-11 04:23 UTC, ras0q reviewed
コメントしました:eyes:

2023-04-11 04:23 UTC, ras0q commented on handler/oauth.go
> +		"code_verifier": {codeVerifier},
codeVerifierを[]byteに変えたことでここに[]byteが入ってきちゃうのが気になりますね(多分動くんですが)
randBytesをstringを返す関数にして`h := sha256.Sum256([]byte(codeVerifier))`みたいな感じにしたらOAuthGenerateCodeHandlerの中はそれなりに綺麗に記述できそうです

2023-04-11 07:07 UTC, ras0q reviewed
多分これだけ！お願いします

2023-04-11 07:07 UTC, ras0q commented on handler/oauth.go
>  }
関数名は`randString`とかにするべきですね
`buf := make([]byte, n)`は https://pkg.go.dev/bytes#NewBufferString を使って https://pkg.go.dev/bytes#Buffer.WriteByte していくのがよさそうです

2023-04-13 04:32 UTC, s9-sukyu commented on handler/oauth.go
>  }
修正したつもりです

2023-04-13 04:35 UTC, ras0q approved these changes
コメントしたとこ消したらマージしてOKです👌

2023-04-13 04:35 UTC, ras0q commented on handler/oauth.go
> +	//buf := make([]byte, n)
ここのコメント消してもらえると🙏

2023-04-13 06:15 UTC, merged