Modify comment and reaction endpoint
traPtitech/Emoine_R pull request #33
Opened 2023-03-03 08:13 UTC by HinaruhiGithub

close #28

2023-03-04 05:53 UTC, ras0q requested changes
すこしだけレビューしました:pray:

2023-03-04 05:53 UTC, ras0q commented on main.go
> +	withLogin.GET("/meeting/:meetingId/reactions", handler.GetReactionFromID)
好みかもなんですが、階層をそろえるためにこの2行は今の43行目の下にあるのが綺麗だと思います
openapiも同様ですね

2023-03-04 05:53 UTC, ras0q commented on main.go
> +	withLogin.GET("/meeting/:meetingId/reactions", handler.GetReactionFromID)
`GetCommentFromID`はcommentIDから取得するように見えるので`GetCommentFromMeetingID`か`GetMeetingComment`の方がよさそうです(多分他と統一するために前者の方がよさそうです)

2023-03-04 06:35 UTC, HinaruhiGithub commented
> すこしだけレビューしました🙏

改修しました。よろしくお願いいたします。

2023-03-05 04:00 UTC, ras0q approved these changes
よさそうです！(CI落ちてるのは気にしなくていいです)

2023-03-05 04:02 UTC, merged