connect-goに切り替えるためにprotobufを作成
traPtitech/Emoine_R pull request #54
Opened 2023-07-21 14:04 UTC by ras0q

ref #52

- :sparkles: define gRPC service
- :wrench: introduce buf

2023-07-21 14:04 UTC, ras0q commented
- [ ] スキーマを書く

2023-07-23 02:57 UTC, kyosu-1 reviewed
元のOpenAPIを確認しつつ全体を見てみました
OAuthの部分だけコメントしましたが、それ以外はよさそうです:thumbsup:

2023-07-23 02:57 UTC, kyosu-1 commented on api/proto/emoine_r/v1/general_api.proto
> +  rpc OAuth2Authorize(OAuth2AuthorizeRequest) returns (google.protobuf.Empty);
OAuth2の認可コードフローをgRPCに載せることは厳しいかも(メソッドが全てPOST＆リダイレクトも表現できないので)

2023-07-27 07:15 UTC, mehm8128 requested changes

2023-07-27 07:15 UTC, mehm8128 commented on api/proto/emoine_r/v1/admin_api.proto
> +}
https://apis.trap.jp/?urls.primaryName=Emoine_R#/token/createToken
ここリクエストボディ足りてなさそうです(他のところも足りないのあるかも)

2023-07-27 07:15 UTC, mehm8128 commented on api/proto/emoine_r/v1/admin_api.proto
> +message UpdateTokenRequest {
移行関係ないけど
これ使わない代わりにrevokeほしいです

2023-07-27 07:15 UTC, mehm8128 commented on api/proto/emoine_r/v1/admin_api.proto
> +message GetTokensResponse {
移行関係ないけど
これ使わないのでいらなさそうです

2023-07-27 07:15 UTC, mehm8128 commented on api/proto/emoine_r/v1/admin_api.proto
> +message GetTokenResponse {
移行関係ないけど
これも多分使わなさそうです

2023-07-27 07:15 UTC, mehm8128 commented on api/proto/emoine_r/v1/admin_api.proto
optionalになっちゃってるのでrequiredつけるのお願いします:pray:

2023-07-27 12:19 UTC, ras0q commented on api/proto/emoine_r/v1/admin_api.proto
proto3はrequiredなくてoptionalだけ後で追加されたっぽいので明らかにoptionalなやつだけ書きます
https://github.com/protocolbuffers/protobuf/issues/2497#issuecomment-267422550

2023-07-27 12:20 UTC, ras0q commented on api/proto/emoine_r/v1/admin_api.proto
> +message GetTokensResponse {
adminがトークン一覧を把握するのに必要だったりしない？
idが分からないとrevokeもできない気がする
(dbを見ればいいと言われればそうだけど)

2023-07-27 12:25 UTC, mehm8128 commented on api/proto/emoine_r/v1/admin_api.proto
> +message GetTokensResponse {
全token一覧はいらなくて、`GetMeetingTokensResponse`を使います

2023-07-27 12:28 UTC, ras0q commented on api/proto/emoine_r/v1/admin_api.proto
> +message GetTokensResponse {
なるほど、じゃあGetTokensもGetTokenもいらないか

2023-07-27 12:29 UTC, mehm8128 commented on api/proto/emoine_r/v1/admin_api.proto
> +message GetTokensResponse {
:desu:

2023-07-27 12:32 UTC, ras0q commented on api/proto/emoine_r/v1/admin_api.proto
> +message GetTokensResponse {
じゃあ全部meetingidに紐づくからGetMeetingTokensとCreateToken/UpdateToken(RevokeToken)が混ざってるのあんまりだな
後者に揃えます

2023-07-27 12:47 UTC, ras0q commented on api/proto/emoine_r/v1/general_api.proto
> +  rpc OAuth2Authorize(OAuth2AuthorizeRequest) returns (google.protobuf.Empty);
OAuth2だけOpenAPIに切り出すのがいいのかな
どうやるのがいいのかわかってない

2023-07-27 13:05 UTC, ras0q commented on api/proto/emoine_r/v1/general_api.proto
> +  rpc OAuth2Authorize(OAuth2AuthorizeRequest) returns (google.protobuf.Empty);
https://github.com/traPtitech/traefik-forward-auth を使うのがいいらしい
https://github.com/traPtitech/NeoShowcase/blob/main/pkg/infrastructure/grpc/auth_interceptor.go

2023-07-27 22:53 UTC, ras0q commented on api/proto/emoine_r/v1/general_api.proto
> +  rpc OAuth2Authorize(OAuth2AuthorizeRequest) returns (google.protobuf.Empty);
でかくなりそうなので別PRでやります

2023-07-28 15:37 UTC, hijiki51 commented
buf使うなら割と簡単に後方互換性きれるので意図してないbreaking changeを防ぐためにもCIでチェックしたほうがいい

bufbuild/buf-breaking-action@v1

2023-07-28 15:38 UTC, hijiki51 commented
あと`buf format --exit-code --diff`でformatのチェックができる

2023-07-29 04:02 UTC, ras0q commented
ファイル分けたらworkflow走らなくなった

2023-07-29 04:24 UTC, ras0q commented
試してたらAPI Limit達したしキャッシュは効いてない

2023-08-08 15:31 UTC, ras0q commented
Go CI / lintが落ちてるのは #50 がマージされてないからで、protobuf CI / Buf Breakingが失敗してるのはマージ先にprotoがないからです

2023-08-09 14:32 UTC, kyosu-1 approved these changes
良さそうです:thumbsup:

2023-08-10 02:37 UTC, merged