connect-goに書き換え
traPtitech/Emoine_R pull request #62
Opened 2023-08-11 05:01 UTC by pirosiki197

2023-08-20 01:32 UTC, ras0q requested changes
:pro:
いくつかコメントしました
結構API変わってて、generalとadminに分けたりもしてるのでファイル構造も変えた方が良さそうですね (別PRでいいです)

2023-08-20 01:32 UTC, ras0q commented on handler/meeting.go
> +			EndedAt:     &timestamppb.Timestamp{Seconds: m.EndedAt.Time.Unix()},
`timestamppb.New`を使うと良さそうです

https://pkg.go.dev/google.golang.org/protobuf/types/known/timestamppb#hdr-Conversion_from_a_Go_Time

2023-08-20 01:32 UTC, ras0q commented on main.go
> +	adminAPIHadnler := handler.NewAdminAPIHandler()
```suggestion
	adminAPIHandler := handler.NewAdminAPIHandler()
```

2023-08-21 15:36 UTC, ras0q reviewed
レビューしました
ここまで書いて`admin_handler.go`とかも作ったならこの前は別PRって言ったけどここで全部移行してもいい気がしました

2023-08-21 15:36 UTC, ras0q commented on handler/admin_handler.go
> +func NewAdminAPIHandler(logger *slog.Logger) *AdminAPIHandler {
ここの返り値`emoine_rv1connect.AdminAPIServiceHandler `にすると`*AdminAPIHandler`が`AdminAPIServiceHandler`を実装していることが明確になるので良いと思います

2023-08-21 15:36 UTC, ras0q commented on handler/general_handler.go
> +func NewGeneralAPIHandler(logger *slog.Logger) *GeneralAPIHandler {
ここも

2023-08-21 15:36 UTC, ras0q commented on handler/meeting.go
> +	h.logger.Info("Video Info", slog.String("video_id", req.Msg.VideoId), slog.String("description", req.Msg.Description))
これdebug用？だったら消しちゃってOKです:ok_hand:

2023-08-21 15:36 UTC, ras0q commented on handler/meeting.go
> +			EndedAt:     lo.Ternary(m.EndedAt.Valid, timestamppb.New(m.EndedAt.Time), nil),
`Description: sql.NullString`や`EndedAt: sql.NullTime`は`.Value() (driver.Value, error)`というメソッドを持っているのでそれを使うと自然だと思います
とりあえずそれ用に`mustValue`を実装しています
基本ないけど↓のときに`m.Description.String`で`"a"`を取得するのはあまり好ましくないはず
```go
sql.NullString{
  String: "a",
  Valid: false
}
```

2023-08-21 15:36 UTC, ras0q commented on go.mod
> +go 1.21
`go mod tidy -go=1.21`するとtoolchainも入るので残しておいていいと思います

2023-08-21 15:36 UTC, ras0q commented on handler/meeting.go
> +		return nil, connect.NewError(connect.CodeInternal, errors.New("ミーティングの作成に失敗しました"))
変更前みたいにユーザーにはエラーの概要だけ見せてログにはエラーの詳細が残るようにしたいですね
一番簡単なのは`h.logger.Error`だけど`connect.Error`に良さげな機能があればそれを使いたい

2023-08-21 15:36 UTC, ras0q commented on handler/meeting.go
> -	}
これが消えててなんでだ？って思ったんですがprotobufの定義が間違ってますね
`GetMeetingsRequest`の`limit`と`optional`に`optional`をつけて`go generate`で再生成してもらえると助かります:pray:

2023-08-21 15:36 UTC, ras0q commented on handler/meeting.go
> +		},
`emoine_rv1.Meeting`と`dbschema.Meeting`の詰め替えを何度かしているので汎用関数を書いてもいいと思います
`pkg/pbconv(ert)`に`func FromDBMeeting(m dbschema.Meeting) emoiner_v1.Meeting`とかを書くと良いかも
(`dbschema.Meeting`にメソッドを生やすと依存が逆転しちゃうので避けてほしいです)

2023-08-22 07:27 UTC, pirosiki197 commented on pkg/pbconv/meeting.go
> +		EndedAt:     timestamppb.New(mustValue[time.Time](m.EndedAt)),
ここ`EndedAt`がnullのときnilじゃなくて`time.Time`のゼロ値を返すようになってます。nilのほうがいいですか？

2023-08-22 07:39 UTC, pirosiki197 commented on go.mod
> +go 1.21
よくわからないまま`go mod edit -go=1.20`と`go mod tidy -go=1.21`したらbuildできなくなっちゃったので助けてください

2023-08-22 08:40 UTC, ras0q commented on go.mod
> +go 1.21
toolchainが1.21からの機能なのに1.20で使おうとしてるとか、、？
手動で1.21使うように書き換えるとどうですか

2023-08-22 08:41 UTC, ras0q commented on go.mod
> +go 1.21
そのあとにgo mod tidyとかがいるかもしれない

2023-08-22 13:17 UTC, pirosiki197 commented on go.mod
> +go 1.21
buildできるようになりました

2023-08-24 07:27 UTC, ras0q reviewed
見ました👀
ファイルの切り分けはgeneral(_handler).goとadmin(_handler).goの2つでいいと思います

2023-08-24 07:27 UTC, ras0q commented on handler/meeting.go
> +	m, err := dbschema.Meetings(ctx, model.DB, int(*req.Msg.Limit), int(*req.Msg.Offset))
生成されたコード見ると
```go
m, err := dbschema.Meetings(ctx, model.DB, int(req.Msg.GetLimit()), int(*req.Msg.GetOffset()))
```
でできるか、、？って一瞬思ったんですがデフォルト値を設定したいので無理ですね

https://github.com/traPtitech/Emoine_R/blob/2fc03244d99e5176437057d77dade416ea6f84c7/docs/openapi.yml#L323-L346 の通りlimitのデフォルトは10なので修正お願いします:pray:

protobufにもデフォルトが10と0であることを書いてあげると親切だと思います (proto3にdefaultの機能はなかった)

2023-08-24 07:27 UTC, ras0q commented on handler/meeting.go
> +		Meeting: pbconv.ToPBMeeting(m),
[IMO]
レビューで`pbconv.FromDBMeeting`と書いたのはパッケージ名からpbにconvertすることが十分伝わると思ったからです (https://pkg.go.dev/strconv を見ると`ToString`みたいな関数はない)

ただpbconvを提案したきっかけがNeoShowcaseで、NeoShowcaseを見るとToPBTargetの形になってたのでまあどっちでもいいと思います
https://github.com/traPtitech/NeoShowcase/tree/main/pkg/infrastructure/grpc/pbconvert

2023-08-24 07:27 UTC, ras0q commented on pkg/pbconv/meeting.go
> +		EndedAt:     timestamppb.New(mustValue[time.Time](m.EndedAt)),
できればnilを返したいですね

mustValue使っても使わなくてもいいのでいい感じに書けると良いです:ok_hand:

2023-08-24 13:47 UTC, ras0q commented
あーtoolchainとかいうの追加したせいでlintが対応してなくて落ちてるわ、まあとりあえず放置でいいです

2023-08-24 15:20 UTC, ras0q approved these changes
書きました
だいたいいいと思うので修正したらマージしてokです

2023-08-24 15:20 UTC, ras0q commented on pkg/pbconv/meeting.go
> +		Description: mustValue[string](m.Description),
ころころ変えて申し訳ないけどlo.Ternary使った方がわかりやすいかも
mustValueは消していいです

2023-08-24 15:20 UTC, ras0q commented on handler/general.go
> +		Meeting: pbconv.FromDBMeeting(*m),
nil pointer dereferenceが怖いので一応m!=nilをチェックしておくと良いです

2023-08-24 15:20 UTC, ras0q commented on handler/general.go
> +		Meeting: pbconv.FromDBMeeting(*m),
dereferenceには注意を払っておくと良いです

2023-08-24 15:20 UTC, ras0q commented on main.go
> +	fmt.Println("Server started")
せっかくだしslogで書くと綺麗かも

2023-08-24 15:39 UTC, merged